server:
  port: 8002

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 139.224.227.35
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/